09-lection7(Postcss migration)
js-tasks-ru/htmlcss-20210812_maksimov-as2 pull request #23
Opened 2021-09-09 12:05 UTC by maksimov-as2

2021-09-09 12:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-09 15:54 UTC, GSemikozov requested changes

2021-09-09 15:54 UTC, GSemikozov commented on src/styles/components/button.scss
> +    &-primary {
здесь и ниже ошибка с описанием модификаторов - нужно через `_`)

2021-09-10 05:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-10 05:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-10 05:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-10 05:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-10 05:32 UTC, maksimov-as2 commented on src/styles/components/button.scss
> +    &-primary {
Исправил

2021-09-10 08:03 UTC, GSemikozov approved these changes

2021-09-10 08:03 UTC, merged