03-lection1\01-button
js-tasks-ru/htmlcss-20210812_maksimov-as2 pull request #3
Opened 2021-08-17 10:35 UTC by maksimov-as2

- normalize.css подключен локально в проект через import в main.css
- в main.css добавлены собственные переменные 
- имплементированы стили в button.css

2021-08-17 10:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-17 12:06 UTC, GSemikozov requested changes

2021-08-17 12:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition:
чтобы не перечислять так много свойств, пожалуй, проще описать транзишн сразу для всех свойств - `all var(--transition-time) ease-in-out`

2021-08-17 12:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    opacity: 0.5;
еще для всех disabled обычно принято добавлять pointer-events: none чтобы пользователь не мог взаимодействовать с такими элементами

2021-08-17 12:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    opacity: 0.5;
и курсор тогда указывать не надо

2021-08-18 13:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-18 13:20 UTC, maksimov-as2 commented on 03-lection1/01-button/button.css
> +    transition:
Изменено на `transition: all var(--transition-time) ease-in-out;`

2021-08-18 13:22 UTC, GSemikozov approved these changes

2021-08-18 13:22 UTC, merged